# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56df7ab1488e8a1f41abccd55db85a06f796cb6d3e144b68bb87e6fb765792d0895c2ed19e5c4a8a487af52dc527e4f0328b8c3b185858d9a1e001ed8ec3a5f5

test:
  secret_key_base: 63da5ea33cf9346519216fba213ccfe6b80eb519f6d94c8ca34cbd8afbe2d8cb5cb83725f849ca2067807d52db995dfe9682b4a3a1ad427edddd6d28c3b50f8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
